"""Guest feedback intelligence, anomalies and the decision log."""

from __future__ import annotations

import json
import re
from pathlib import Path as FsPath

from fastapi import APIRouter, HTTPException, Query

from api.app import services

router = APIRouter(prefix="/api", tags=["intelligence"])
ROOT = FsPath(__file__).resolve().parents[3]


@router.get("/guest-intelligence/overview",
            summary="AI guest-feedback summary (reads stored, validated output)")
def gi_overview() -> dict:
    return services.guest_intelligence_overview()


@router.get("/guest-intelligence/aspects",
            summary="Aspect volume by category and polarity")
def gi_aspects() -> dict:
    return {"aspects": services.guest_aspects()}


@router.get("/guest-intelligence/issues",
            summary="Buried complaints - negative aspects inside 4+ star reviews")
def gi_issues(limit: int = Query(25, ge=1, le=100)) -> dict:
    return {
        "note": ("these are the reviews a document-level sentiment classifier would "
                 "score as positive and discard. Every row quotes its source verbatim."),
        "issues": services.guest_issues(limit),
    }


@router.get("/guest-intelligence/benchmark",
            summary="Gemini vs a deterministic keyword baseline")
def gi_benchmark() -> dict:
    return {
        "ground_truth": ("generator-derived, NOT human-annotated. Measures recovery of "
                         "deliberately injected aspects, not agreement with human "
                         "judgement. No claim of the latter is made."),
        "results": services.ai_benchmark(),
    }


@router.get("/anomalies",
            summary="Detected anomalies with baseline, deviation and drivers")
def anomalies() -> dict:
    """Served from the generated report so a page load costs no recomputation.

    Regenerated by scripts/run_anomaly_detection.py, which also verifies the detector
    against ground truth: F1/F2/F3 found, and the D1 decoy correctly silent.
    """
    md = ROOT / "reports" / "anomalies.md"
    if not md.exists():
        raise HTTPException(status_code=503, detail="Anomaly report not generated yet.")

    rows = []
    for line in md.read_text(encoding="utf-8").splitlines():
        if line.startswith("| `") and line.count("|") >= 9:
            cells = [x.strip().strip("`") for x in line.strip("|").split("|")]
            if len(cells) >= 9 and cells[0] != "Metric":
                rows.append({
                    "metric": cells[0],
                    "segment": cells[1],
                    "date": cells[2],
                    "actual": cells[3],
                    "baseline": cells[4],
                    "deviation_pct": cells[5],
                    "robust_z": cells[6],
                    "confidence": cells[7],
                    "likely_drivers": cells[8] if cells[8] not in ("-", "—") else None,
                })

    return {
        "method": ("day-of-week aware trailing baseline, robust MAD scale, dual "
                   "thresholds (statistical AND material), published false-alert budget"),
        "why_not_isolation_forest": ("on a weekly-seasonal univariate series it flags "
                                     "every weekend, misses the weekday running below "
                                     "its own weekday norm, and yields no baseline or "
                                     "explanation, so its output cannot be acted on"),
        "count": len(rows),
        "anomalies": rows[:50],
    }


def _field(body: str, label: str) -> str | None:
    """Pull a bolded table field such as **Status** | Open."""
    m = re.search(rf"\*\*{label}\*\*\s*\|?\s*([^\n|]+)", body)
    return m.group(1).strip(" |") if m else None


def _paragraph(body: str, label: str) -> str | None:
    """Pull a bolded lead-in paragraph such as **Finding.** ..."""
    m = re.search(rf"\*\*{label}\.?\*\*\s*(.+?)(?=\n\n|\n\*\*|\Z)", body, re.S)
    if not m:
        return None
    return re.sub(r"\s+", " ", re.sub(r"[*`]", "", m.group(1))).strip()


@router.get("/decisions",
            summary="Decision log - finding, evidence, confidence, action")
def decisions() -> dict:
    """Parsed from the generated DECISION_LOG.md, which is built from live queries."""
    md = ROOT / "DECISION_LOG.md"
    if not md.exists():
        raise HTTPException(status_code=503, detail="Decision log not generated yet.")

    parts = re.split(r"\n## (D-\d+) · ", md.read_text(encoding="utf-8"))
    entries = []
    for i in range(1, len(parts) - 1, 2):
        did, body = parts[i], parts[i + 1]
        entries.append({
            "id": did,
            "title": body.splitlines()[0].strip(),
            "status": _field(body, "Status"),
            "owner": _field(body, "Owner"),
            "confidence": _field(body, "Confidence"),
            "finding": _paragraph(body, "Finding"),
            "recommendation": _paragraph(body, "Recommendation"),
        })

    return {
        "note": ("the target role states that success is measured by decisions made, "
                 "not reports produced. One entry is a decision NOT to act; one was "
                 "reversed when follow-up data contradicted the first read."),
        "count": len(entries),
        "decisions": entries,
    }


@router.get("/daily-brief/latest", summary="Most recent automated operations brief")
def brief_latest() -> dict:
    md = ROOT / "reports" / "LATEST_BRIEF.md"
    stamp = ROOT / "reports" / "_freshness.json"
    if not md.exists():
        raise HTTPException(status_code=503, detail="No brief generated yet.")
    meta = json.loads(stamp.read_text(encoding="utf-8")) if stamp.exists() else {}
    return {
        "generated_at_utc": meta.get("generated_at_utc"),
        "as_of": meta.get("as_of"),
        "quality_score": meta.get("quality_score"),
        "alerts": meta.get("alerts_today"),
        "note": ("every number in the brief is computed in SQL or pandas and passed to "
                 "the template as a fact - no language model calculates anything in it"),
        "markdown": md.read_text(encoding="utf-8"),
    }


@router.get("/daily-brief/history", summary="Available brief dates")
def brief_history() -> dict:
    d = ROOT / "reports" / "briefings"
    files = sorted((p.stem for p in d.glob("*.md")), reverse=True) if d.exists() else []
    return {"count": len(files), "dates": files[:60]}


@router.get("/copilot/capabilities",
            summary="What Ask StayPulse can and cannot be asked")
def copilot_capabilities() -> dict:
    """The tool list and the refusal contract. Calls no model.

    The refusals are part of the contract, not gaps in it: pricing, overbooking
    levels and revenue-uplift claims cannot be settled from this warehouse, and
    the copilot is built to say so rather than produce a plausible number.
    """
    return services.copilot_capabilities()


@router.get("/copilot/ask", summary="Ask a question over the deterministic layer")
def copilot_ask(
    question: str = Query(..., min_length=3, max_length=500,
                          description="A question about this portfolio"),
) -> dict:
    """Answer a question by calling deterministic tools, then phrasing the result.

    The model selects tools and writes the explanation; it never computes. Every
    figure in the answer comes from the tool results, which are returned
    alongside the prose so a caller can render numbers from structured output
    rather than from a sentence. Each answer also carries a numeric-fidelity
    report checking the prose against the tool output.

    This endpoint calls Gemini and therefore costs quota. It is the only one in
    this API that does.
    """
    try:
        return services.copilot_ask(question)
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(
            status_code=503,
            detail=(
                "The copilot is unavailable. It requires GEMINI_API_KEY to be "
                "configured; every other endpoint in this API works without it."
            ),
        ) from exc
