"""API tests.

The security tests are the ones that matter most here: an analytics API that leaks a
connection string in an error message is worse than no API. Two of them force
failures rather than waiting to observe one, because a sanitiser that has never been
exercised is indistinguishable from one that does not work.

Run:  python -m pytest tests/test_api.py -v
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from fastapi.testclient import TestClient  # noqa: E402

from api.app import services  # noqa: E402
from api.app.main import ALLOWED_ORIGINS, app  # noqa: E402

logging.disable(logging.INFO)

client = TestClient(app)
# Separate client for the error-path tests: the default re-raises server exceptions
# instead of letting the handler produce a response.
error_client = TestClient(app, raise_server_exceptions=False)

READ_ONLY_ENDPOINTS = [
    "/health",
    "/health/readiness",
    "/",
    "/api/kpis/overview",
    "/api/revenue/trends",
    "/api/revenue/channels",
    "/api/properties",
    "/api/operations/overview",
    "/api/operations/sla",
    "/api/operations/service-requests",
    "/api/guest-intelligence/overview",
    "/api/guest-intelligence/aspects",
    "/api/guest-intelligence/issues",
    "/api/guest-intelligence/benchmark",
    "/api/anomalies",
    "/api/decisions",
    "/api/daily-brief/latest",
    "/api/daily-brief/history",
    "/api/data-quality/overview",
    "/api/data-quality/rules",
    "/api/metrics",
    "/api/pipeline-runs",
    "/api/revenue-management/overview",
    "/api/revenue-management/on-the-books",
    "/api/revenue-management/pickup",
    "/api/revenue-management/pace",
    "/api/revenue-management/signals",
    "/api/revenue-management/booking-curve",
    "/api/revenue-management/lead-time",
    "/api/revenue-management/wash",
    "/api/revenue-management/grain-reconciliation",
    "/api/revenue-management/forecast",
    "/api/revenue-management/forecast/accuracy",
    "/api/revenue-management/replay",
    "/api/revenue-management/replay/summary",
    "/api/revenue-management/replay/evaluation",
    "/api/revenue-management/forecast/intervals",
    "/api/revenue-management/forecast/intervals/coverage",
    "/api/revenue-management/backtest-lab",
    "/api/revenue-management/why",
]


class TestHealth:
    def test_health_is_instant_and_does_no_io(self):
        """Render pings this constantly; touching the DB here risks restart loops."""
        r = client.get("/health")
        assert r.status_code == 200
        assert r.json() == {"status": "ok"}

    def test_health_reveals_no_infrastructure(self):
        body = client.get("/health").text.lower()
        for leak in ("host", "user", "password", "supabase", "pooler", "postgres"):
            assert leak not in body

    def test_readiness_reports_database_without_exposing_it(self):
        r = client.get("/health/readiness")
        assert r.status_code == 200
        data = r.json()
        assert data["database"] in ("reachable", "unreachable")
        if data["database"] == "reachable":
            assert data["analytical_tables"] > 0
        assert "PGPASSWORD" not in r.text
        # The engine banner is fine; a host or username is not.
        assert "pooler.supabase.com" not in r.text


class TestEndpointsRespond:
    @pytest.mark.parametrize("endpoint", READ_ONLY_ENDPOINTS)
    def test_returns_200(self, endpoint):
        r = client.get(endpoint)
        assert r.status_code == 200, f"{endpoint} -> {r.status_code}: {r.text[:200]}"

    def test_index_lists_its_own_endpoints(self):
        listed = client.get("/").json()["endpoints"]
        # The count check is not decoration. When the index was generated by
        # walking app.routes it returned an EMPTY list, and this loop passed
        # because iterating nothing raises nothing.
        assert len(listed) >= 30, (
            f"index advertises only {len(listed)} endpoints; it has gone stale or "
            "empty, and the loop below would pass vacuously"
        )
        # Every advertised endpoint must actually resolve. A stale index is a
        # broken promise a reviewer will click on.
        for path in listed:
            if "{" in path:
                continue
            assert client.get(path).status_code == 200, f"advertised but broken: {path}"

    def test_index_advertises_every_public_endpoint(self):
        """The index and the OpenAPI contract must not disagree."""
        listed = set(client.get("/").json()["endpoints"])
        schema = {
            p for p, ops in client.get("/openapi.json").json()["paths"].items()
            if "get" in ops and (p.startswith("/api") or p.startswith("/health"))
        }
        assert listed == schema, f"index missing {schema - listed}, extra {listed - schema}"


class TestSemanticLayerParity:
    """The API must not become a second definition of any metric."""

    def test_revpar_identity_holds_in_api_response(self):
        d = client.get("/api/kpis/overview").json()
        occ = d["occupancy_pct"] / 100.0
        assert abs(d["revpar_inr"] - d["adr_inr"] * occ) < 1.0

    def test_kpis_declare_their_date_basis(self):
        d = client.get("/api/kpis/overview").json()
        assert d["date_basis"] == "stay_date"
        assert d["is_synthetic"] is True

    def test_api_matches_direct_database_query(self):
        from staypulse import db
        api = client.get("/api/kpis/overview").json()
        direct = db.fetch_all("""
            SELECT count(*) FILTER (WHERE is_sellable) av,
                   count(*) FILTER (WHERE is_occupied) sold
            FROM mart.fact_unit_night
        """)[0]
        assert api["rooms_available"] == int(direct["av"])
        assert api["rooms_sold"] == int(direct["sold"])

    def test_comparison_window_is_same_length(self):
        d = client.get("/api/kpis/overview?days=30").json()
        assert d["comparison"] is not None
        assert d["period"]["trailing_days"] == 30

    def test_metric_registry_is_served(self):
        metrics = client.get("/api/metrics").json()["metrics"]
        assert len(metrics) >= 14
        assert all(m["date_basis"] for m in metrics)
        assert all(m["caveats"] for m in metrics)


class TestValidation:
    def test_rejects_out_of_range_days(self):
        assert client.get("/api/kpis/overview?days=0").status_code == 422
        assert client.get("/api/kpis/overview?days=9999").status_code == 422

    def test_rejects_unknown_grain(self):
        assert client.get("/api/revenue/trends?grain=fortnight").status_code == 422
        assert client.get("/api/revenue/trends?grain=month").status_code == 200

    def test_rejects_bad_property_key(self):
        assert client.get("/api/properties/0/performance").status_code == 422
        assert client.get("/api/properties/abc/performance").status_code == 422

    def test_missing_property_is_404_not_500(self):
        r = client.get("/api/properties/99999/performance")
        assert r.status_code == 404

    def test_limit_is_capped(self):
        assert client.get("/api/guest-intelligence/issues?limit=101").status_code == 422
        assert client.get("/api/guest-intelligence/issues?limit=5").status_code == 200


class TestSecurity:
    def test_no_secret_value_appears_in_any_response(self):
        from staypulse import config
        config.load_env()
        secrets = [v for k in ("PGPASSWORD", "GEMINI_API_KEY", "OPENWEATHER_API_KEY",
                               "PGHOST", "PGUSER")
                   if (v := os.environ.get(k)) and len(v) >= 8]
        if not secrets:
            pytest.skip("no credentials configured in this environment")
        for endpoint in READ_ONLY_ENDPOINTS:
            text = client.get(endpoint).text
            for secret in secrets:
                assert secret not in text, f"{endpoint} leaked a credential"

    def test_driver_error_is_sanitised(self, monkeypatch):
        """Force a realistic psycopg failure and confirm nothing escapes.

        A real connection error message contains the host, the port and the
        username. That must never reach a client.
        """
        boom = ("connection to server at 1.2.3.4 port 5432 failed: "
                "password authentication failed for user secretuser")

        def explode(*_a, **_k):
            raise RuntimeError(boom)

        monkeypatch.setattr(services.db, "fetch_all", explode)
        r = error_client.get("/api/kpis/overview")
        assert r.status_code == 503
        for leak in ("1.2.3.4", "secretuser", "password authentication", "Traceback"):
            assert leak not in r.text
        assert r.json()["error"] == "analytics_unavailable"

    def test_no_write_methods_are_exposed(self):
        """Read-only by construction: nothing here can mutate the warehouse.

        Read from the OpenAPI schema, NOT from `app.routes`. On FastAPI 0.141 /
        Starlette 1.6 included routers sit in `app.routes` as opaque
        `_IncludedRouter` entries, so walking it sees only the four default docs
        routes plus `/` -- and this assertion passed for months without ever
        examining a single one of the 34 real endpoints. A security test that
        inspects nothing is worse than no security test, because it reads as
        coverage.

        The count assertion below is what stops it silently going hollow again.
        """
        paths = client.get("/openapi.json").json()["paths"]
        assert len(paths) >= 30, (
            f"only {len(paths)} paths visible; if this collapses, the scan below "
            "is inspecting almost nothing and the test has gone vacuous"
        )
        for path, operations in paths.items():
            mutating = {m.upper() for m in operations} & {"POST", "PUT", "PATCH", "DELETE"}
            assert not mutating, f"mutating method {mutating} exposed on {path}"

    def test_cors_allows_the_production_origin(self):
        origin = "https://stay-pulse-ai-hospitality-analytics.vercel.app"
        assert origin in ALLOWED_ORIGINS
        r = client.get("/health", headers={"Origin": origin})
        assert r.headers.get("access-control-allow-origin") == origin

    def test_cors_rejects_an_unknown_origin(self):
        r = client.get("/health", headers={"Origin": "https://evil.example.com"})
        assert r.headers.get("access-control-allow-origin") != "https://evil.example.com"

    def test_no_wildcard_cors(self):
        assert "*" not in ALLOWED_ORIGINS


class TestObservability:
    def test_request_id_and_timing_headers(self):
        r = client.get("/health")
        assert len(r.headers.get("X-Request-Id", "")) == 12
        assert r.headers.get("X-Response-Time-Ms", "").isdigit()

    def test_openapi_schema_is_valid(self):
        s = client.get("/openapi.json").json()
        assert s["info"]["title"] == "StayPulse Analytics API"
        assert len(s["paths"]) >= 20
        # Every path needs a summary, or /docs is unusable in an interview.
        for path, ops in s["paths"].items():
            for method, op in ops.items():
                assert op.get("summary"), f"{method.upper()} {path} has no summary"

    def test_docs_are_served(self):
        assert client.get("/docs").status_code == 200
        assert client.get("/redoc").status_code == 200


class TestRevenueManagementEndpoints:
    def test_as_of_defaults_inside_the_dataset(self):
        """Anchored to the data, not the wall clock, or the book goes empty."""
        d = client.get("/api/revenue-management/overview").json()
        assert d["nights_on_books_30d"] > 0
        assert d["stay_dates_scored"] > 0

    def test_bad_as_of_is_rejected_not_ignored(self):
        assert client.get("/api/revenue-management/pace?as_of=not-a-date").status_code == 422
        assert client.get("/api/revenue-management/pace?as_of=2019-01-01").status_code == 422

    def test_unknown_forecast_model_is_rejected(self):
        assert client.get(
            "/api/revenue-management/forecast?model=magic"
        ).status_code == 422

    def test_grain_identity_is_served_and_holds(self):
        d = client.get("/api/revenue-management/grain-reconciliation").json()
        assert d["identity_holds"] is True
        assert (
            d["exploded_booking_nights"]
            - d["less_unallocated_nights"]
            + d["plus_hourly_unit_nights"]
            == d["equals_occupied_unit_nights"]
        )

    def test_pace_counts_add_up(self):
        d = client.get("/api/revenue-management/pace").json()
        c = d["counts"]
        assert c["scored"] == c["behind"] + c["on_track"] + c["ahead"]

    def test_forecast_accuracy_discloses_where_the_model_loses(self):
        """The default model is beaten at 30 days and the API must say so."""
        d = client.get("/api/revenue-management/forecast/accuracy").json()
        assert d["best_by_horizon"]["30"] != "pickup" or d["best_by_horizon"][30] != "pickup"
        assert client.get("/api/revenue-management/forecast").json()["caveat"]

    def test_why_decomposition_sums_to_the_movement(self):
        d = client.get("/api/revenue-management/why?days=30").json()
        total = sum(c["revpar_contribution_inr"] for c in d["components"])
        assert abs(total - d["change"]) < 0.05

    def test_why_states_no_llm_is_involved(self):
        d = client.get("/api/revenue-management/why").json()
        assert "no language model" in d["method"].lower()

    def test_signals_never_recommend_a_price(self):
        body = client.get("/api/revenue-management/signals").text.lower()
        for phrase in ("increase rate", "lower rate", "reprice", "raise price"):
            assert phrase not in body


class TestDecisionReplayEndpoint:
    """The replay endpoint has to keep the decision and the outcome apart."""

    def test_decision_declares_the_rule_bounding_every_input(self):
        d = client.get(
            "/api/revenue-management/replay?as_of=2026-06-01&with_outcome=false"
        ).json()
        sources = d["decision"]["information_set"]
        assert len(sources) >= 6, (
            "an empty information set would make the loop below inspect nothing"
        )
        for source in sources:
            assert source["temporal_rule"]
            assert source["basis"] in {"realised", "as_booked", "ex_ante"}

    def test_withholding_the_outcome_actually_withholds_it(self):
        body = client.get(
            "/api/revenue-management/replay?as_of=2026-06-01&with_outcome=false"
        )
        assert "outcome" not in body.json()
        assert "actual_room_nights" not in body.text

    def test_outcome_is_served_separately_and_is_populated(self):
        d = client.get(
            "/api/revenue-management/replay?as_of=2026-06-01&horizon_days=30"
        ).json()
        assert d["outcome"]["forecast_accuracy"], "outcome present but empty"
        assert d["outcome"]["coverage"]["resolvable_days"] > 0

    def test_the_same_as_of_date_replays_identically(self):
        url = "/api/revenue-management/replay?as_of=2026-06-01&with_outcome=false"
        assert client.get(url).json()["fingerprint"] == client.get(url).json()["fingerprint"]

    def test_evaluation_publishes_the_base_rate_next_to_the_hit_rate(self):
        d = client.get("/api/revenue-management/replay/evaluation").json()
        pace = d["pace"]
        assert pace["base_rate_below_expectation_pct"] is not None, (
            "a precision figure without its base rate is not a result"
        )
        assert pace["behind"]["recall_pct"] is not None, (
            "precision without recall reports only the flattering half"
        )
        assert pace["naive_sign_of_gap"]["below_median_at_as_of"]["calls"] > 0


class TestHonesty:
    def test_synthetic_data_is_disclosed(self):
        assert "synthetic" in client.get("/").text.lower()
        assert client.get("/api/kpis/overview").json()["is_synthetic"] is True

    def test_ai_ground_truth_limitation_is_disclosed(self):
        body = client.get("/api/guest-intelligence/benchmark").json()
        assert "generator-derived" in body["ground_truth"]
        assert "NOT human-annotated" in body["ground_truth"]

    def test_quality_score_explains_why_it_is_below_100(self):
        d = client.get("/api/data-quality/overview").json()
        assert d["quality_score"] < 100
        assert "deliberate" in d["note"] or "planted" in d["note"]


class TestForecastIntervalEndpoints:
    """An interval endpoint that does not publish its coverage is a shaded band."""

    def test_every_point_carries_bounds_that_bracket_it(self):
        d = client.get(
            "/api/revenue-management/forecast/intervals?horizon_days=14"
        ).json()
        rows = d["forecast"]
        assert len(rows) == 14
        priced = [r for r in rows if r["lower_room_nights"] is not None]
        assert priced, "no row carried an interval; the loop below is vacuous"
        for row in priced:
            assert row["lower_room_nights"] <= row["predicted_room_nights"]
            assert row["predicted_room_nights"] <= row["upper_room_nights"]
            assert row["lower_room_nights"] >= 0

    def test_a_wider_level_gives_a_wider_band(self):
        def width(level):
            rows = client.get(
                f"/api/revenue-management/forecast/intervals?horizon_days=7&level={level}"
            ).json()["forecast"]
            spans = [r["upper_room_nights"] - r["lower_room_nights"]
                     for r in rows if r["lower_room_nights"] is not None]
            assert spans, f"no bounds produced at level {level}"
            return sum(spans) / len(spans)
        assert width(0.5) < width(0.8) < width(0.95)

    def test_coverage_publishes_out_of_sample_beside_in_sample(self):
        d = client.get(
            "/api/revenue-management/forecast/intervals/coverage"
        ).json()
        rows = d["coverage"]
        assert len(rows) >= 6, "coverage table is empty or truncated"
        for row in rows:
            assert row["out_of_sample_pct"] is not None
            assert row["in_sample_pct"] is not None

    def test_the_published_method_meets_its_nominal_level(self):
        d = client.get(
            "/api/revenue-management/forecast/intervals/coverage"
        ).json()
        default = [r for r in d["coverage"] if r["is_default"]]
        assert default, "no method is marked as published"
        for row in default:
            assert abs(row["deviation_pp"]) <= 6.0, (
                f"{row['method']} at {row['level']:.0%} covered "
                f"{row['out_of_sample_pct']}% out of sample"
            )

    def test_an_unknown_level_is_rejected(self):
        assert client.get(
            "/api/revenue-management/forecast/intervals?level=0.99"
        ).status_code == 422

    def test_lab_slices_are_served_and_name_what_they_cannot_slice(self):
        d = client.get("/api/revenue-management/backtest-lab").json()
        slices = d["slices"]
        for dimension in ("by_horizon", "by_month", "by_weekday",
                          "by_holiday_adjacency"):
            assert slices[dimension], f"{dimension} is empty"
        assert "per-property forecast target" in slices["not_sliced"]["by_property"]
