"""Load generated data into the mart.

Dimensions go in first so their identity keys exist; facts are then key-mapped
and streamed with COPY, which is the difference between seconds and minutes over
a pooled connection to a hosted database.
"""

from __future__ import annotations

import io
from typing import Any

import pandas as pd
from sqlalchemy import text

from staypulse import db
from staypulse.generate.builder import GeneratedData

# dim_date is generated by migration 002 and is never truncated here: it is
# reference data, not generated data.
TRUNCATE_ORDER = [
    "mart.fact_review_aspect",
    "mart.fact_review",
    "mart.fact_inventory_movement",
    "mart.fact_service_request",
    "mart.fact_payment",
    "mart.fact_unit_night",
    "mart.fact_booking",
    "mart.dim_request_type",
    "mart.dim_staff",
    "mart.dim_guest",
    "mart.dim_channel",
    "mart.dim_unit",
    "mart.dim_property",
]


def _copy_frame(conn, table: str, frame: pd.DataFrame) -> int:
    """Stream a DataFrame into a table with COPY ... FROM STDIN (CSV)."""
    if frame.empty:
        return 0
    cols = list(frame.columns)
    buf = io.StringIO()
    frame.to_csv(buf, index=False, header=False, na_rep="")
    buf.seek(0)
    collist = ", ".join(f'"{c}"' for c in cols)
    sql = f"COPY {table} ({collist}) FROM STDIN WITH (FORMAT csv, NULL '')"
    with conn.connection.driver_connection.cursor() as cur:
        with cur.copy(sql) as copy:
            copy.write(buf.read())
    return len(frame)


def _key_map(conn, table: str, natural: str, surrogate: str) -> dict[Any, int]:
    rows = conn.execute(text(f"SELECT {natural}, {surrogate} FROM {table}")).all()
    return {r[0]: r[1] for r in rows}


def _as_nullable_int(frame: pd.DataFrame, *columns: str) -> pd.DataFrame:
    """Coerce columns to pandas nullable Int64.

    A plain .map() that yields any NaN silently upcasts an integer column to
    float64, so a surrogate key serialises as "12.0" and COPY rejects it as
    invalid input for bigint. Int64 keeps the integers integral and renders
    missing values as empty, which is what COPY ... NULL '' expects.
    """
    out = frame.copy()
    for col in columns:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce").astype("Int64")
    return out


def truncate_mart() -> None:
    with db.connect() as conn:
        for table in TRUNCATE_ORDER:
            conn.execute(text(f"TRUNCATE TABLE {table} RESTART IDENTITY CASCADE"))


def load(data: GeneratedData) -> dict[str, int]:
    """Load a generated dataset. Returns rows written per table."""
    written: dict[str, int] = {}
    engine = db.get_engine()

    with engine.begin() as conn:
        # ---- dimensions -------------------------------------------------
        written["dim_property"] = _copy_frame(conn, "mart.dim_property", data.properties)
        prop_map = _key_map(conn, "mart.dim_property", "property_code", "property_key")

        units = data.units.copy()
        units["property_key"] = units["property_code"].map(prop_map)
        units = _as_nullable_int(units, "property_key", "sqft", "floor")
        written["dim_unit"] = _copy_frame(
            conn, "mart.dim_unit",
            units[["unit_code", "property_key", "unit_type", "bedrooms",
                   "max_occupancy", "sqft", "floor", "base_rate_inr", "is_sellable"]])
        unit_map = _key_map(conn, "mart.dim_unit", "unit_code", "unit_key")

        written["dim_channel"] = _copy_frame(conn, "mart.dim_channel", data.channels)
        chan_map = _key_map(conn, "mart.dim_channel", "channel_code", "channel_key")

        written["dim_request_type"] = _copy_frame(
            conn, "mart.dim_request_type", data.request_types)
        rt_rows = conn.execute(
            text("SELECT category, subcategory, request_type_key FROM mart.dim_request_type")
        ).all()
        rt_map = {(r[0], r[1]): r[2] for r in rt_rows}

        staff = data.staff.copy()
        staff["property_key"] = staff["property_code"].map(prop_map)
        staff = _as_nullable_int(staff, "property_key")
        written["dim_staff"] = _copy_frame(
            conn, "mart.dim_staff",
            staff[["staff_id", "full_name", "role", "property_key", "shift",
                   "joined_on", "left_on", "is_active"]])

        # Identity normalisation happens on load, not in the source: this is the
        # ETL's job and the before/after repeat rate is a reportable finding.
        guests = data.guests.copy()
        guests["email_normalised"] = (
            guests["email"].str.lower().str.replace(r"\.(?=[^@]*@)", "", regex=True))
        guests["phone_last10"] = (
            guests["phone"].str.replace(r"\D", "", regex=True).str[-10:])
        guests["first_seen_date"] = None
        guests["is_duplicate_of"] = None
        guests = _as_nullable_int(guests, "is_duplicate_of")
        written["dim_guest"] = _copy_frame(
            conn, "mart.dim_guest",
            guests[["guest_id", "full_name", "email", "phone", "email_normalised",
                    "phone_last10", "home_city", "guest_segment", "first_seen_date",
                    "is_duplicate_of"]])
        guest_map = _key_map(conn, "mart.dim_guest", "guest_id", "guest_key")

        # ---- bookings ---------------------------------------------------
        b = data.bookings.copy()
        b["guest_key"] = b["guest_id"].map(guest_map)
        b["property_key"] = b["property_code"].map(prop_map)
        b["unit_key"] = b["unit_code"].map(unit_map)
        b["channel_key"] = b["channel_code"].map(chan_map)
        b["gst_amount_inr"] = 0.0
        b["source_system"] = "pms"
        booking_cols = [
            "booking_id", "guest_key", "property_key", "unit_key", "channel_key",
            "booked_at", "booking_date", "check_in_date", "check_out_date",
            "cancelled_at", "cancel_date", "stay_type", "nights", "adults", "status",
            "gross_amount_inr", "discount_inr", "net_room_amount_inr",
            "gst_amount_inr", "commission_inr", "lead_time_days", "source_system",
        ]
        b = _as_nullable_int(b, "guest_key", "property_key", "unit_key", "channel_key",
                             "nights", "adults", "lead_time_days")
        written["fact_booking"] = _copy_frame(conn, "mart.fact_booking", b[booking_cols])
        booking_map = _key_map(conn, "mart.fact_booking", "booking_id", "booking_key")

        # ---- unit nights ------------------------------------------------
        un = data.unit_nights.copy()
        un["unit_key"] = un["unit_code"].map(unit_map)
        un["property_key"] = un["property_code"].map(prop_map)
        un["booking_key"] = un["booking_id"].map(booking_map)
        un["channel_key"] = un["channel_code"].map(chan_map)
        un["gst_inr"] = 0.0
        un = _as_nullable_int(un, "unit_key", "property_key", "date_key", "booking_key",
                              "channel_key")
        written["fact_unit_night"] = _copy_frame(
            conn, "mart.fact_unit_night",
            un[["unit_key", "property_key", "stay_date", "date_key", "booking_key",
                "channel_key", "is_sellable", "is_occupied", "is_out_of_order",
                "is_complimentary", "room_revenue_net_inr", "gst_inr", "commission_inr"]])

        # ---- payments ---------------------------------------------------
        p = data.payments.copy()
        # Deliberately a LEFT-join-shaped map: an unresolvable reference becomes
        # NULL and is counted, not dropped.
        p["booking_key"] = p["booking_id_raw"].map(booking_map)
        p["source_system"] = "gateway"
        p = _as_nullable_int(p, "booking_key")
        written["fact_payment"] = _copy_frame(
            conn, "mart.fact_payment",
            p[["payment_id", "booking_key", "booking_id_raw", "paid_at", "payment_date",
               "settled_at", "settlement_date", "method", "gross_amount_inr",
               "gateway_fee_inr", "gst_on_fee_inr", "net_credited_inr", "is_refund",
               "status", "source_system"]])

        # ---- service requests -------------------------------------------
        sr = data.service_requests.copy()
        sr["property_key"] = sr["property_code"].map(prop_map)
        sr["unit_key"] = sr["unit_code"].map(unit_map)
        sr["booking_key"] = sr["booking_id"].map(booking_map)
        sr["guest_key"] = sr["guest_id"].map(guest_map)
        sr["request_type_key"] = sr.apply(
            lambda r: rt_map.get((r["category"], r["subcategory"])), axis=1)
        sr["assigned_staff_key"] = None
        sr = _as_nullable_int(sr, "property_key", "unit_key", "booking_key", "guest_key",
                              "request_type_key", "assigned_staff_key", "sla_minutes",
                              "resolution_minutes", "reopened_count", "csat_score")
        written["fact_service_request"] = _copy_frame(
            conn, "mart.fact_service_request",
            sr[["request_id", "property_key", "unit_key", "booking_key", "guest_key",
                "request_type_key", "assigned_staff_key", "created_at", "request_date",
                "first_response_at", "resolved_at", "resolved_date", "priority",
                "status", "channel", "sla_minutes", "resolution_minutes",
                "is_sla_breached", "reopened_count", "csat_score"]])

        # ---- reviews ----------------------------------------------------
        rv = data.reviews.copy()
        rv["property_key"] = rv["property_code"].map(prop_map)
        rv["booking_key"] = rv["booking_id"].map(booking_map)
        rv["guest_key"] = rv["guest_id"].map(guest_map)
        rv["channel_key"] = rv["channel_code"].map(chan_map)
        rv = _as_nullable_int(rv, "property_key", "booking_key", "guest_key", "channel_key")
        written["fact_review"] = _copy_frame(
            conn, "mart.fact_review",
            rv[["review_id", "property_key", "booking_key", "guest_key", "channel_key",
                "reviewed_at", "review_date", "rating", "review_text", "language",
                "is_synthetic_text"]])

        # ---- inventory --------------------------------------------------
        inv = data.inventory.copy()
        inv["property_key"] = inv["property_code"].map(prop_map)
        inv = _as_nullable_int(inv, "property_key")
        written["fact_inventory_movement"] = _copy_frame(
            conn, "mart.fact_inventory_movement",
            inv[["property_key", "movement_date", "item_code", "item_name",
                 "opening_qty", "received_qty", "consumed_qty", "wastage_qty",
                 "closing_qty", "unit_cost_inr"]])

    return written
