"""Execute every curated analysis in sql/analysis/ and render the results.

Each file answers one business question and carries its question, method and date
basis in a header comment. Running them all is the regression test for the
analytics layer: a query that stops returning rows after a schema change is a
broken analysis, not a silent one.

Usage:
    python scripts/run_analyses.py
    python scripts/run_analyses.py --out reports/analyses.md
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from staypulse import db  # noqa: E402

SQL_DIR = PROJECT_ROOT / "sql" / "analysis"
MAX_ROWS = 15


def header_of(sql: str) -> tuple[str, str]:
    """Pull the BUSINESS QUESTION and DATE BASIS out of the leading comment."""
    question, basis = "", ""
    lines = [ln[2:].strip() if ln.startswith("--") else ln for ln in sql.splitlines()]
    for i, ln in enumerate(lines):
        if ln.startswith("BUSINESS QUESTION"):
            parts = []
            for x in lines[i + 1:]:
                t = x.strip()
                # Stop at a blank line or the next ALL-CAPS section heading.
                if not t or re.match(r"^[A-Z][A-Z /-]{3,}$", t):
                    break
                parts.append(t.strip('"'))
            question = " ".join(parts).strip()
        if ln.startswith("DATE BASIS"):
            basis = ln.split(":", 1)[-1].strip()
    return question, basis


def fmt(v) -> str:
    if v is None:
        return "—"
    if isinstance(v, (int,)):
        return f"{v:,}"
    if isinstance(v, float):
        return f"{v:,.2f}"
    s = str(v)
    from decimal import Decimal
    if isinstance(v, Decimal):
        return f"{float(v):,.2f}"
    return s


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=str, default=None)
    args = ap.parse_args()

    files = sorted(SQL_DIR.glob("*.sql"))
    if not files:
        print("no analyses found")
        return 1

    md: list[str] = [
        "# Curated hospitality analyses",
        "",
        "Every query answers one business question and declares its date basis.",
        "Generated by `scripts/run_analyses.py` against the synthetic warehouse.",
        "",
        "**All figures derive from clearly-labelled synthetic data.**",
        "",
    ]
    failed = 0

    for path in files:
        sql = path.read_text(encoding="utf-8")
        question, basis = header_of(sql)
        title = path.stem.split("_", 1)[1].replace("_", " ").title()
        print(f"\n{'=' * 84}\n{path.name}\n  Q: {question}\n  date basis: {basis}\n{'=' * 84}")

        md += [f"## {title}", "", f"**Question.** {question}", ""]
        if basis:
            md += [f"**Date basis.** `{basis}`", ""]

        try:
            rows = db.fetch_all(sql)
        except Exception as exc:  # noqa: BLE001
            failed += 1
            msg = f"{type(exc).__name__}: {exc}"
            print(f"  [FAIL] {msg[:300]}")
            md += [f"> **Query failed.** `{msg[:200]}`", ""]
            continue

        if not rows:
            print("  (no rows)")
            md += ["_No rows returned._", ""]
            continue

        cols = list(rows[0].keys())
        shown = rows[:MAX_ROWS]

        widths = {c: max(len(c), *(len(fmt(r[c])) for r in shown)) for c in cols}
        print("  " + " | ".join(c.ljust(widths[c]) for c in cols))
        print("  " + "-+-".join("-" * widths[c] for c in cols))
        for r in shown:
            print("  " + " | ".join(fmt(r[c]).ljust(widths[c]) for c in cols))
        if len(rows) > MAX_ROWS:
            print(f"  ... {len(rows) - MAX_ROWS} more rows")

        md += ["| " + " | ".join(cols) + " |",
               "|" + "|".join("---" for _ in cols) + "|"]
        for r in shown:
            md.append("| " + " | ".join(fmt(r[c]) for c in cols) + " |")
        if len(rows) > MAX_ROWS:
            md.append(f"\n_… {len(rows) - MAX_ROWS} further rows._")
        md += ["", f"<details><summary>SQL — `{path.name}`</summary>", "",
               "```sql", sql.strip(), "```", "", "</details>", "", "---", ""]

    print(f"\n{len(files)} analyses run, {failed} failed")

    if args.out:
        out = PROJECT_ROOT / args.out
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(md), encoding="utf-8")
        print(f"written to {out}")

    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
